---
apiVersion: v1
kind: Service
metadata:
  name: statsd-exporter
  namespace: lgtm
spec:
  type: ClusterIP
  ports:
    - port: 9125
      targetPort: 9125
      protocol: UDP
      name: statsd-udp
    - port: 9102
      targetPort: 9102
      protocol: TCP
      name: metrics
  selector:
    app: statsd-exporter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: statsd-exporter
  namespace: lgtm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statsd-exporter
  template:
    metadata:
      labels:
        app: statsd-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9102"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: statsd-exporter
          image: prom/statsd-exporter:v0.26.0
          args:
            - --statsd.mapping-config=/etc/statsd/mapping.yml
          ports:
            - containerPort: 9125
              protocol: UDP
              name: statsd-udp
            - containerPort: 9102
              protocol: TCP
              name: metrics
          volumeMounts:
            - name: statsd-mapping
              mountPath: /etc/statsd
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "250m"
      volumes:
        - name: statsd-mapping
          configMap:
            name: statsd-mapping-config
