---
apiVersion: v1
kind: Service
metadata:
  name: mimir
  namespace: lgtm
spec:
  type: ClusterIP
  ports:
    - port: 9009
      targetPort: 9009
      protocol: TCP
      name: http
  selector:
    app: mimir
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mimir
  namespace: lgtm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mimir
  template:
    metadata:
      labels:
        app: mimir
    spec:
      containers:
        - name: mimir
          image: grafana/mimir:latest
          args:
            - '-config.file=/etc/mimir/mimir.yaml'
          ports:
            - containerPort: 9009
              name: http
          volumeMounts:
            - name: mimir-config
              mountPath: /etc/mimir
            - name: mimir-storage
              mountPath: /data
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
      volumes:
        - name: mimir-config
          configMap:
            name: mimir-config
        - name: mimir-storage
          emptyDir: {}
